// <auto-generated by AudioConductor>
#if UNITY_EDITOR
using UnityEditor;

namespace ThanhDV.AudioConductor.FMOD
{
    public class PlatformChooserDesktop
    {
        [MenuItem(Common.MENU_ITEM + "Platform/Desktop", false, 0)]
        public static void Choose()
        {
            PlatformChooser.ChangeDefaultProjectPlatform("Desktop");
        }

        [MenuItem(Common.MENU_ITEM + "Platform/Desktop", true)]
        public static bool ValidateChoose()
        {
            string menuPath = Common.MENU_ITEM + "Platform/Desktop";
            Menu.SetChecked(menuPath, PlatformChooser.IsDefaultPlatform("Desktop"));
            return true;
        }
    }
}
#endif
