using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using FMODUnity;
using UnityEditor;
using UnityEngine;

namespace ThanhDV.AudioConductor.FMOD
{
    public class PlatformChooser
    {
        private const string GeneratedHeader = "// <auto-generated by AudioConductor>";

        [MenuItem(Common.MENU_ITEM + "Platform/Refresh", false, 1)]
        public static void Refresh()
        {
            if (!FMODEditorPreflight.TryGetSettings(out Settings settings, out string error) ||
                !FMODEditorPreflight.TryResolveBankDirectory(settings, out string bankDirectory, out error) ||
                !FMODEditorPreflight.TryValidateRequiredBanks(settings, bankDirectory, out _, out _, out error))
            {
                Debug.LogError($"[AudioConductor - FMOD] {error}");
                return;
            }

            if (!TryBuildGeneratedScripts(settings, out Dictionary<string, string> generatedScripts, out error))
            {
                Debug.LogError($"[AudioConductor - FMOD] {error}");
                return;
            }

            if (!TryCommitGeneratedScripts(generatedScripts, out bool changed, out error))
            {
                Debug.LogError($"[AudioConductor - FMOD] {error}");
                return;
            }

            if (changed) AssetDatabase.Refresh();
        }

        private static bool TryBuildGeneratedScripts(
            Settings settings,
            out Dictionary<string, string> generatedScripts,
            out string error)
        {
            generatedScripts = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            error = null;

            if (!settings.HasPlatforms) return true;

            string[] platformDirectories;
            try
            {
                platformDirectories = Directory.GetDirectories(settings.SourceBankPath, "*", SearchOption.TopDirectoryOnly);
                Array.Sort(platformDirectories, StringComparer.Ordinal);
            }
            catch (Exception e)
            {
                error = $"Failed to enumerate FMOD platform directories: {e.Message}";
                return false;
            }

            var usedClassNames = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < platformDirectories.Length; i++)
            {
                string platformDirectory = platformDirectories[i];
                if (!FMODEditorPreflight.TryValidateRequiredBanks(settings, platformDirectory, out _, out _, out _))
                {
                    continue;
                }

                string buildDirectory = Path.GetFileName(platformDirectory);
                if (string.IsNullOrWhiteSpace(buildDirectory)) continue;

                string className = MakeUniqueIdentifier($"PlatformChooser{MakeSafeIdentifier(buildDirectory)}", usedClassNames);
                string scriptPath = $"{Common.FMOD_PLATFORM_SCRIPT_FOLDER}/{className}{Common.SCRIPT_EXTENSION}";
                generatedScripts.Add(scriptPath, BuildPlatformChooserSource(buildDirectory, className));
            }

            if (generatedScripts.Count == 0)
            {
                error = $"No valid FMOD platform directories containing the required banks were found in '{settings.SourceBankPath}'.";
                return false;
            }

            return true;
        }

        private static string BuildPlatformChooserSource(string buildDirectory, string className)
        {
            string escapedBuildDirectory = EscapeForCSharpStringLiteral(buildDirectory);
            var sb = new StringBuilder();

            sb.AppendLine(GeneratedHeader);
            sb.AppendLine($"#if UNITY_EDITOR");
            sb.AppendLine($"using UnityEditor;");
            sb.AppendLine($"");
            sb.AppendLine($"namespace ThanhDV.AudioConductor.FMOD");
            sb.AppendLine("{");
            sb.AppendLine($"    public class {className}");
            sb.AppendLine("    {");
            sb.AppendLine($"        [MenuItem(Common.MENU_ITEM + \"Platform/{escapedBuildDirectory}\", false, 0)]");
            sb.AppendLine("        public static void Choose()");
            sb.AppendLine("        {");
            sb.AppendLine($"            PlatformChooser.ChangeDefaultProjectPlatform(\"{escapedBuildDirectory}\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        [MenuItem(Common.MENU_ITEM + \"Platform/{escapedBuildDirectory}\", true)]");
            sb.AppendLine("        public static bool ValidateChoose()");
            sb.AppendLine("        {");
            sb.AppendLine($"            string menuPath = Common.MENU_ITEM + \"Platform/{escapedBuildDirectory}\";");
            sb.AppendLine($"            Menu.SetChecked(menuPath, PlatformChooser.IsDefaultPlatform(\"{escapedBuildDirectory}\"));");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine($"#endif");

            return sb.ToString();
        }

        public static void ChangeDefaultProjectPlatform(string buildDirectory)
        {
            if (string.IsNullOrWhiteSpace(buildDirectory))
            {
                Debug.LogError("[AudioConductor - FMOD] FMOD build directory cannot be null or empty.");
                return;
            }

            Settings settings = Settings.Instance;
            if (settings == null)
            {
                Debug.LogError("[AudioConductor - FMOD] FMOD settings asset is not available.");
                return;
            }

            Platform defaultPlatform = settings.DefaultPlatform;
            if (defaultPlatform == null)
            {
                Debug.LogError("[AudioConductor - FMOD] FMOD Default platform is not available.");
                return;
            }

            string platformBankDirectory;
            try
            {
                string sourceBankDirectory = Path.GetFullPath(settings.SourceBankPath);
                platformBankDirectory = Path.GetFullPath(Path.Combine(sourceBankDirectory, buildDirectory));

                StringComparison pathComparison =
                    Application.platform == RuntimePlatform.WindowsEditor
                        ? StringComparison.OrdinalIgnoreCase
                        : StringComparison.Ordinal;

                if (!string.Equals(
                        Path.GetDirectoryName(platformBankDirectory),
                        sourceBankDirectory.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
                        pathComparison))
                {
                    Debug.LogError("[AudioConductor - FMOD] The selected platform must be a direct child of the FMOD source bank directory.");
                    return;
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"[AudioConductor - FMOD] Failed to resolve the selected platform directory: {e.Message}");
                return;
            }

            if (!FMODEditorPreflight.TryValidateRequiredBanks(settings, platformBankDirectory, out _, out _, out string error))
            {
                Debug.LogError($"[AudioConductor - FMOD] The selected platform is not a valid FMOD bank build: {error}");
                return;
            }

            SerializedObject serializedPlatform = new(defaultPlatform);
            SerializedProperty buildDirectoryValueProp = serializedPlatform.FindProperty("Properties.BuildDirectory.Value");
            SerializedProperty buildDirectoryHasValueProp = serializedPlatform.FindProperty("Properties.BuildDirectory.HasValue");
            // SerializedProperty speakerModeValueProp = serializedPlatform.FindProperty("Properties.SpeakerMode.Value");
            // SerializedProperty speakerModeHasValueProp = serializedPlatform.FindProperty("Properties.SpeakerMode.HasValue");

            if (buildDirectoryValueProp == null || buildDirectoryHasValueProp == null)
            {
                Debug.LogError("[AudioConductor - FMOD] Could not find FMOD serialized BuildDirectory properties.");
                return;
            }

            Undo.RecordObject(defaultPlatform, "Change FMOD Default Project Platform");

            serializedPlatform.Update();
            buildDirectoryValueProp.stringValue = buildDirectory;
            buildDirectoryHasValueProp.boolValue = true;

            // if (speakerModeValueProp != null && speakerModeHasValueProp != null)
            // {
            //     speakerModeValueProp.intValue = (int)defaultPlatform.SpeakerMode;
            //     speakerModeHasValueProp.boolValue = true;
            // }

            serializedPlatform.ApplyModifiedProperties();

            EditorUtility.SetDirty(defaultPlatform);
            EditorUtility.SetDirty(settings);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[AudioConductor - FMOD] FMOD Default Project Platform changed to '{buildDirectory}'.");
        }

        public static bool IsDefaultPlatform(string buildDirectory)
        {
            if (string.IsNullOrWhiteSpace(buildDirectory)) return false;

            Settings settings = Settings.Instance;
            if (settings == null || settings.DefaultPlatform == null) return false;

            return string.Equals(settings.DefaultPlatform.BuildDirectory, buildDirectory, StringComparison.Ordinal);
        }

        private static string MakeUniqueIdentifier(string baseIdentifier, HashSet<string> usedIdentifiers)
        {
            if (usedIdentifiers.Add(baseIdentifier)) return baseIdentifier;

            int suffix = 2;
            while (true)
            {
                string candidate = $"{baseIdentifier}_{suffix}";
                if (usedIdentifiers.Add(candidate)) return candidate;
                suffix++;
            }
        }

        private static string MakeSafeIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw)) return "Unnamed";

            raw = raw.Trim();
            var sb = new StringBuilder(raw.Length);

            for (int i = 0; i < raw.Length; i++)
            {
                char c = raw[i];
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            }

            if (sb.Length == 0) sb.Append("Unnamed");
            if (!char.IsLetter(sb[0]) && sb[0] != '_') sb.Insert(0, '_');

            return sb.ToString();
        }

        private static string EscapeForCSharpStringLiteral(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;

            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
        }

        private static bool TryCommitGeneratedScripts(
            Dictionary<string, string> desiredScripts,
            out bool changed,
            out string error)
        {
            changed = false;
            error = null;

            try
            {
                var ownedScripts = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (Directory.Exists(Common.FMOD_PLATFORM_SCRIPT_FOLDER))
                {
                    string[] existingScripts = Directory.GetFiles(
                        Common.FMOD_PLATFORM_SCRIPT_FOLDER,
                        "PlatformChooser*.cs",
                        SearchOption.TopDirectoryOnly);

                    for (int i = 0; i < existingScripts.Length; i++)
                    {
                        string scriptPath = existingScripts[i].Replace('\\', '/');
                        if (IsGeneratedPlatformScript(scriptPath)) ownedScripts.Add(scriptPath);
                    }
                }

                var scriptsToWrite = new List<KeyValuePair<string, string>>();
                foreach (KeyValuePair<string, string> desiredScript in desiredScripts)
                {
                    if (File.Exists(desiredScript.Key) && !ownedScripts.Contains(desiredScript.Key))
                    {
                        error = $"Platform script '{desiredScript.Key}' already exists without the AudioConductor generated header. No files were changed.";
                        return false;
                    }

                    if (!File.Exists(desiredScript.Key) ||
                        !string.Equals(File.ReadAllText(desiredScript.Key), desiredScript.Value, StringComparison.Ordinal))
                    {
                        scriptsToWrite.Add(desiredScript);
                    }
                }

                var scriptsToDelete = new List<string>();
                foreach (string ownedScript in ownedScripts)
                {
                    if (!desiredScripts.ContainsKey(ownedScript)) scriptsToDelete.Add(ownedScript);
                }

                if (scriptsToWrite.Count == 0 && scriptsToDelete.Count == 0) return true;

                string transactionDirectory = Path.Combine(
                    "Library",
                    "AudioConductor",
                    "PlatformRefresh",
                    Guid.NewGuid().ToString("N"));
                var backups = new List<FileBackup>();
                var installedScripts = new List<string>();
                var stagedScripts = new List<string>(scriptsToWrite.Count);
                bool outputFolderCreated = false;
                bool preserveTransactionDirectory = false;

                try
                {
                    Directory.CreateDirectory(transactionDirectory);

                    for (int i = 0; i < scriptsToWrite.Count; i++)
                    {
                        string stagedPath = Path.Combine(transactionDirectory, $"script-{i}.tmp");
                        File.WriteAllText(stagedPath, scriptsToWrite[i].Value, new UTF8Encoding(false));
                        stagedScripts.Add(stagedPath);
                    }

                    if (scriptsToWrite.Count > 0 && !Directory.Exists(Common.FMOD_PLATFORM_SCRIPT_FOLDER))
                    {
                        Directory.CreateDirectory(Common.FMOD_PLATFORM_SCRIPT_FOLDER);
                        outputFolderCreated = true;
                    }

                    for (int i = 0; i < scriptsToWrite.Count; i++)
                    {
                        string targetPath = scriptsToWrite[i].Key;
                        if (File.Exists(targetPath)) BackupFile(targetPath, transactionDirectory, backups);

                        File.Move(stagedScripts[i], targetPath);
                        installedScripts.Add(targetPath);
                    }

                    for (int i = 0; i < scriptsToDelete.Count; i++)
                    {
                        string scriptPath = scriptsToDelete[i];
                        BackupFile(scriptPath, transactionDirectory, backups);

                        string metaPath = scriptPath + ".meta";
                        if (File.Exists(metaPath)) BackupFile(metaPath, transactionDirectory, backups);
                    }

                    changed = true;
                    return true;
                }
                catch (Exception e)
                {
                    try
                    {
                        for (int i = installedScripts.Count - 1; i >= 0; i--)
                        {
                            if (File.Exists(installedScripts[i])) File.Delete(installedScripts[i]);
                        }

                        for (int i = backups.Count - 1; i >= 0; i--)
                        {
                            FileBackup backup = backups[i];
                            if (File.Exists(backup.OriginalPath)) File.Delete(backup.OriginalPath);
                            if (File.Exists(backup.BackupPath)) File.Move(backup.BackupPath, backup.OriginalPath);
                        }

                        if (outputFolderCreated &&
                            Directory.Exists(Common.FMOD_PLATFORM_SCRIPT_FOLDER) &&
                            Directory.GetFileSystemEntries(Common.FMOD_PLATFORM_SCRIPT_FOLDER).Length == 0)
                        {
                            Directory.Delete(Common.FMOD_PLATFORM_SCRIPT_FOLDER);
                        }

                        error = $"Platform script refresh failed and existing files were restored: {e.Message}";
                    }
                    catch (Exception rollbackError)
                    {
                        preserveTransactionDirectory = true;
                        error =
                            $"Platform script refresh failed: {e.Message}. " +
                            $"Automatic restore also failed: {rollbackError.Message}. " +
                            $"Recovery files were retained at '{transactionDirectory}'.";
                    }

                    changed = false;
                    return false;
                }
                finally
                {
                    if (!preserveTransactionDirectory)
                    {
                        try
                        {
                            if (Directory.Exists(transactionDirectory)) Directory.Delete(transactionDirectory, true);
                        }
                        catch (Exception cleanupError)
                        {
                            Debug.LogWarning($"[AudioConductor - FMOD] Could not remove platform refresh temporary files: {cleanupError.Message}");
                        }
                    }
                }
            }
            catch (Exception e)
            {
                error = $"Failed to prepare platform script refresh: {e.Message}";
                return false;
            }
        }

        private static bool IsGeneratedPlatformScript(string scriptPath)
        {
            using (var reader = new StreamReader(scriptPath, Encoding.UTF8, true))
            {
                return string.Equals(reader.ReadLine(), GeneratedHeader, StringComparison.Ordinal);
            }
        }

        private static void BackupFile(string originalPath, string transactionDirectory, List<FileBackup> backups)
        {
            string backupPath = Path.Combine(
                transactionDirectory,
                $"backup-{backups.Count}-{Path.GetFileName(originalPath)}");

            File.Move(originalPath, backupPath);
            backups.Add(new FileBackup(originalPath, backupPath));
        }

        private sealed class FileBackup
        {
            public readonly string OriginalPath;
            public readonly string BackupPath;

            public FileBackup(string originalPath, string backupPath)
            {
                OriginalPath = originalPath;
                BackupPath = backupPath;
            }
        }
    }
}